### ISSUE TITLE
Stderr Acknowledgement

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis-installer#12]
As suggested by @p0mvn , we should capture any stderror that gets output and require the user to acknowledge it. As it stands now, all errors are not shown to the user.

The main complication is that the sdk sometimes prints random things to stderror. I will have to play with it a bit to find which commands behave incorrectly and see if we can make a work around for it.

**Comment by niccoloraspa** [comment]
Added better error management in #58
