### ISSUE TITLE
CI Automation

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis-installer#32]
We need to look into some kind of automation that utilizes flags to ensure a node is able to hit blocks when starting from scratch. Right now, every time I get a report of the installer not working, I need to manually start up a node and go through the setup process. Automating will save a lot of man hours to check if it works with the click of a button / on PRs

**Comment by niccoloraspa** [comment]
Duplicated: https://github.com/osmosis-labs/osmosis-installer/issues/43
