### ISSUE TITLE
use official way to install Docker

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis-installer#40]
The current installation source of Docker is faulty. It does not work well with the e2e.

We should change it to the following:
https://docs.docker.com/engine/install/ubuntu/#set-up-the-repository

That seems to be working okay.

This is useful for quickly setting up the environment on new VMs.

**Comment by p0mvn** [comment]
CC: @czarcas7ic for awareness

**Comment by ValarDragon** [comment]
Wait why does get.osmosis.zone relate to docker?

**Comment by p0mvn** [comment]
There is a flow that fully sets up a development environment for contracts, including dependencies such as Docker
