### ISSUE TITLE
Osmosis installer should check the required golang version

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-installer#42]
We added a required golang version recently for osmosis, so we should ensure the installer is installing the right one. Currently its accepting a go 1.18, preventing installation of go 1.19.

(I wonder if it'd be a QOL win, to have a make command in osmosis that could install recommended golang version)

**Comment by ValarDragon** [comment]
One way to do this is clone the osmosis repo and checkout the tag first, read the go.mod for golang version, and then install that version.

**Comment by niccoloraspa** [comment]
removed golang installation from the current installer version, this no longer apply.
If we wish to have golang, we can re-open an issue to add  that functionality
