### ISSUE TITLE
Create docker testing suites for the installer

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-installer#43]
We should ideally have tests that this sets up various services correctly. I feel like one way to do it, would be a docker test that spins up a new instance of every OS, then just goes through the default pruned full node path, and checks if it has a node that is syncing against mainnet. (And can be killed + restarted)

**Comment by niccoloraspa** [comment]
Added initial test here: https://github.com/osmosis-labs/osmosis-installer/blob/main/.github/workflows/test-client.yaml 
I will create an issue to test the `node` install
