### ISSUE TITLE
Osmosis Bash Installer V2

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis-installer#5]
V2 should include (for a release in the next sprint)
- [x] State Sync (I'm trying to hold out for the fix to be more permanent, but I can include the temp fix for now)
- [x] Mac ARM compatibility
- [x] Pruning methods (aggressive pruning, default, archive) (specifically make it so that users downloading archive don't prune)
- [x] Custom ports
- [x] Client node (no swap update, no state dl option, just inits db and changes IP blockapsis endpoint)
- [x] Ability to choose installation directory (currently just installs default location)
- [x] Mac compatibility
- [x] Replay from genesis (Will have to find a way to capture the chain halting due to version mismatch on python, update version, then restart)

No longer needed:
- [x] Windows compatibility
- [x] Download releases

**Comment by ValarDragon** [comment]
One other component that would be really cool is being able to use this to setup a node just as a client. E.g. like Lens, but unique to osmosis.

Basically installs binary, doesn't update swap, doesn't download state, but does update client.toml

**Comment by czarcas7ic** [comment]
Love it and 100 percent easily doable! Should I also change the node from querying localhost to instead query a public node by default?

**Comment by ValarDragon** [comment]
yeah that'd be great! For now perhaps we set it to blockapsis endpoint, until we can get another provider or the fallback nodes idea
