### ISSUE TITLE
Error: error unmarshalling result: illegal base64 data at input byte 4

### ISSUE THREAD

**Issue by jasmeenPedalsup** [osmosis-labs/osmosis-installer#66]
Hey, I'm getting this error when trying to deploy a wasm smart contract on the testchain:
`error unmarshalling result: illegal base64 data at input byte 4`

Here is the command I'm running:
`RES=$(osmosisd tx wasm store ./artifacts/cw_tpl_osmosis.wasm --from wallet --gas-prices 1uosmo --gas auto --gas-adjustment 1.3 -y --output json -b block)`

**output**
gas estimate: 1239877
Error: error unmarshalling result: illegal base64 data at input byte 4

when I visit mintscan where I saw my transaction was successful you can check below link
https://testnet.mintscan.io/osmosis-testnet/txs/A30983836F3B01A49F6EA9C1B52CEAB8453939FFAAB38D51CFE6C3D36441F246

when I run below commnad
`osmosisd query wasm list-contract-by-code 5836`

it return below result
`contracts: []
pagination:
  next_key: null
  total: "0"
`

what I am doing wrong and how can I resolve this issue?

I am following below docs
https://docs.osmosis.zone/cosmwasm/testnet/cosmwasm-deployment

**Comment by niccoloraspa** [comment]
Closing the issue as not relevant to the installer. 
For these types of questions please check out our Discord!
